# Generated by Django 2.1.5 on 2019-01-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answers'),
            preserve_default=False,
        ),
    ]
