# Generated by Django 2.1.5 on 2019-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190121_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(blank=True, default='img/default.jpeg', null=True, upload_to=''),
        ),
    ]
