# Generated by Django 2.1.5 on 2019-01-21 17:47

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
