# Generated by Django 2.1.5 on 2019-01-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoices',
            name='is_correct',
        ),
    ]
