# Generated by Django 2.1.5 on 2019-01-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_questionchoices_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionImage'),
        ),
    ]
